language: go

go:
  - '1.8'
  - '1.9.x'
  - 1.x
  - master

script:
  - go test -v ./...
  - '[ -z "$(gofmt -s -l .)" ] || { gofmt -s -d -e . ; return 1; } '

matrix:
  allow_failures:
    - go: master
